<?php
$this->headTitle($this->pageTitle)
?>

<h1><?= $this->pageTitle ?></h1>
<div class="row">
    <div class="col">
        <form action="/toc/<?= $this->id_book ?>" method="get">
            <div class="form-group">
                <label for="exampleTextarea" class="form-label">条文</label>
                <!-- class="form-control" を追加 -->
                <textarea readonly class="form-control" id="exampleTextarea" style="height: 400px;"><?= $this->article ?></textarea>
                <br/>
            </div>
        </form>
    </div>
    <div class="col">
        <form action="/toc/<?= $this->id_book ?>" method="get">
            <div class="form-group">
                <label for="exampleTextarea" class="form-label">コメント</label>
                <!-- class="form-control" を追加 -->
                <textarea class="form-control" id="exampleTextarea" style="height: 400px;"><?= $this->article ?></textarea>
                <br/>
                <button type="submit" class="btn btn-outline-primary btn-sm">戻る</button>
                <button type="submit" class="btn btn-outline-primary btn-sm">更新</button>
            </div>
        </form>
    </div>
</div>