<?php
$config = require __DIR__ . '/../../config/config.php';
$books = $config['books'] ?? [];
?>
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/favicon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>PreBar</title>
    <style>
        body {
            padding-top: 56px; /* Navbarの高さに合わせて調整してください */
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
    <div class="container">
        <!-- ロゴやサイト名 -->
        <a class="navbar-brand" href="/">
            <img src='/img/logo.jpg' alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
            PreBar
        </a>

        <!-- スマホ用ハンバーガーボタン -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- メニュー項目 -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- 動的なメニュー項目: 詰められるだけ詰める -->
                <li class="nav-item mt-2 mt-lg-0">
                    <div class="d-flex flex-wrap gap-1">
                        <?php foreach ($books as $book): ?>
                            <a class="btn btn-outline-primary btn-sm" href="/toc/<?= $book['id'] ?>">
                                <?= $book['abbr'] ?>
                            </a>
                        <?php endforeach ?>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-4">
    <?= $this->content ?>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
